### ISSUE TITLE
List of Events

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/userStory#2]
## Value Proposition

**As a** beaver **I need** an overview of fitness courses **to be able to** live an active and healthy life

## Description

![Screenshot 2022-12-09 at 14 55 21](https://user-images.githubusercontent.com/116001730/206718010-d56bfc31-df2d-4442-9cb0-c5e44db3e22f.png)

## Acceptance Criteria

- [ ] a headline with name of the site
- [ ] a list of events
- [ ] work with dummy data

## Tasks

(for developers team)

- [ ] adjust the page title
- [ ] create a header component
- [ ] create dummy data for course list
- [ ] render course list

**Comment by WalterRestifo** [comment]
Hi Andy, ich würde den Footer in eine andere Userstory einbauen. Ich denke, wir sollen keine Buttons einbauen, die keine aktuelle Funktion haben. Das mit dem Bookmarkbutton sehe ich auch so. Es kann aber sein, dass ich mich irre

**Comment by andy-schwedler** [comment]
> Hi Andy, ich würde den Footer in eine andere Userstory einbauen. Ich denke, wir sollen keine Buttons einbauen, die keine aktuelle Funktion haben. Das mit dem Bookmarkbutton sehe ich auch so. Es kann aber sein, dass ich mich irre

Danke für dein Feedback! Hast recht, ich packe das in eigene stories, dann hab ich ein paar kleinere Todos, falls ich ne Lücke habe 👌

**Comment by AntjeWalter** [comment]
Hi Andy, ich würde den Teil "to be able to" noch anpassen. Das finde ich etwas zu allgemein formuliert, erstmal wollen die User ja einen Überblick über die Kurse, um sich zu informieren, wann welcher Kurs stattfindet, oder? Das alleinige angucken der Kurse und Kurszeiten führt ja nicht dazu, dass sie gesund leben... :D

**Comment by julialoeschel** [comment]
Hey, 
Ich stimme mit Antje überein :) 
Ansonsten ist mir noch aufgefallen, dass das Bild von den AC abweicht 
- es ist keine Überschrift zu sehen
- es ist eine Navigation da, die in der AC nicht berücksichtigt wird. 
Das Bild sollte auf keinen Fall etwas anderes Darstellen als was im Text steht, sondern diesen unterstützen. 

Sonst eine Super Story

**Comment by andy-schwedler** [comment]
Hi @AntjeWalter & @julialoeschel,

danke für euer Feedback. Ihr habt natürlich beide sowas von Recht. 

Hab euer Feedback direkt umgesetzt. 

Grüße aus dem Süden!
