### ISSUE TITLE
Filter for course list

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/userStory#3]
## Value Proposition

**As a** beaver **I need** a filter option of courses **to be able to** quickly find a  course

## Acceptance Criteria

- [ ] A headline with name of the site
- [ ] A list of Events
- [ ] work with dummy data

## Tasks

(for developers team)

- [ ] create dummy data for course list
- [ ] render course list
- [ ] create a header component
- [ ] adjust the page title
