### ISSUE TITLE
add Images to each event

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/userStory#5]
## Value Proposition

**As a** sporty beaver **I need** **to be able to** quickly recognise an event by its picture

## Description

![Screenshot 2022-12-09 at 16 02 25](https://user-images.githubusercontent.com/116001730/206731295-88f00920-4f08-4b92-a8a5-9fe8ac38e247.png)

## Acceptance Criteria

- [ ] applicable picture for each event category

## Tasks

- [ ] Create pictures for event categories
- [ ] add image to component
