### ISSUE TITLE
add bookmark button

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/userStory#6]
## Value Proposition

As a beaver I need a bookmark button to remember certain events

## Description

![Screenshot 2022-12-09 at 16 10 34](https://user-images.githubusercontent.com/116001730/206732773-644c2bbf-1ef3-4471-8d4b-bf52a2c9e879.png)

## Acceptance Criteria

- [ ] bookmark button
- [ ] bookmark section

## Tasks

- [ ] Insert a bookmark button
- [ ] Insert a bookmark filter
- [ ] add bookmark button to navigation
