### ISSUE TITLE
add project setup

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/userStory#7]
## Value Proposition

As a developer I need a setup a new project

## Description

no pic

## Acceptance Criteria

- [ ] new project setup

## Tasks

- [ ] Create a new project with `create-next-app@latest beaver-fit`
- [ ] Connect project to GitHub
- [ ] Clean up files which are not needed
- [ ] Commit and **after** this, create a first new branch for this task
