### ISSUE TITLE
create details page for each memory card

### ISSUE THREAD

**Issue by andy-schwedler** [andy-schwedler/userStory#8]
## Value Proposition

As a beaver I need an overview of a memory 
to be able to fully remember all details of a certain situation
in order to remember what happened exactly.

## Description

could look like this

![Image](https://user-images.githubusercontent.com/116001730/207892369-6ee926d3-3187-49e0-aefa-9eccf04a9e1a.png)

## Acceptance Criteria

- click on each card to open more details
- Location should be displayed as Link

## Tasks

- [x] update initial data with location and description
- [x] create dynamic routing for each rendered card
- [x] create location link and forward beaver (user) to Google Maps
- [x] add styling

**Comment by ufelgen** [comment]
Hey Andy, 
[so](https://www.youtube.com/watch?v=NcKGw-IO5Uc) fühl ich mich, wenn ich deine value proposition lese 🙈 vielleicht magst du das noch etwas umformulieren/spezifizieren?

sonst finde ich ist es eine gute User Story! "each memory has a link" ist irgendwie das gleiche wie eine Zeile drüber oder? und du beschreibst es ja in den Tasks mit dynamic routing, also ich glaube das kannst du aus den acceptance criteria löschen :)

**Comment by andy-schwedler** [comment]
Gotcha! 😂  das Feedback nehme ich gerne an und setze es sofort um. Hab vielen Dank für deinen Input.
